services:
  backend:
    build:
      context: ./backend
    container_name: rag-backend-container
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}

    container_name: rag-frontend-container

    ports:
      - "5173:80"

    depends_on:
      - backend